#!/usr/bin/env python3
"""Generate a zenith per-target config directory from a cFS build.

Reads a spec file describing which telemetry structs to extract from
which ELF files, pulls their exact layouts out of the DWARF debug
info via gdb, and writes the target directory zenith consumes:

    <out>/app_manifest.json      component names, uids, dict joins
    <out>/structs/<comp>.json    one zenith struct dict per component

The layouts come from the same binaries the flight software runs --
not from headers, docs, or memory -- so the dictionaries cannot
drift from the wire. Rerun after any flight software rebuild.

Spec format (JSON):
{
  "application": "cFS cpu1",
  "entries": [
    { "component": "cfe_es",            # dict key (dataFile stem)
      "name": "CFE_ES",                 # display name in zenith
      "elf": "path/to/core-cpu1",       # binary holding the DWARF
      "type": "CFE_ES_HousekeepingTlm_t",
      "apid": "0x000",                  # SPP APID on the wire
      "uid": "0x00C00000" },            # zenith routing uid
    ...
  ]
}

Prints the apid_map block for config.toml when done.

Usage: dictgen.py <spec.json> <output-dir>
"""

import json
import os
import subprocess
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))


def extract(elf: str, entries: list) -> list:
    spec = [{"component": e["component"], "type": e["type"]} for e in entries]
    env = dict(os.environ, DICTGEN_SPEC=json.dumps(spec))
    proc = subprocess.run(
        ["gdb", "-batch", "-nx", "-ex", f"file {elf}",
         "-x", os.path.join(HERE, "gdb_extract.py")],
        capture_output=True, text=True, env=env, check=False,
    )
    out = proc.stdout
    if "DICTGEN_BEGIN" not in out:
        sys.exit(f"gdb extraction failed for {elf}:\n{proc.stderr or out}")
    payload = out.split("DICTGEN_BEGIN")[1].split("DICTGEN_END")[0]
    return json.loads(payload)


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    spec = json.load(open(sys.argv[1]))
    out_dir = sys.argv[2]
    structs_dir = os.path.join(out_dir, "structs")
    os.makedirs(structs_dir, exist_ok=True)

    by_elf = defaultdict(list)
    for e in spec["entries"]:
        by_elf[e["elf"]].append(e)

    results = {}
    for elf, entries in by_elf.items():
        for r in extract(elf, entries):
            results[r["component"]] = r

    manifest = {"application": spec["application"],
                "description": "Generated by cfs-dictgen from build DWARF",
                "components": []}
    for e in spec["entries"]:
        r = results[e["component"]]
        dict_json = {
            "component": e["component"],
            "structs": {
                "Housekeeping": {
                    "category": "TELEMETRY",
                    "size": r["size"],
                    "fields": r["fields"],
                }
            },
        }
        path = os.path.join(structs_dir, f"{e['component']}.json")
        with open(path, "w") as f:
            json.dump(dict_json, f, indent=2)
            f.write("\n")
        manifest["components"].append({
            "name": e["name"],
            "fullUid": e["uid"],
            "type": "telemetry",
            "dataFile": f"{e['component']}.json",
            "notes": f"{r['struct']} from {os.path.basename(e['elf'])}",
        })
        emit = sum(1 for f in r["fields"] if f["type"] in ("uint", "int", "float"))
        print(f"{e['name']}: {r['struct']} -> {r['size']}B payload, "
              f"{len(r['fields'])} fields ({emit} numeric)")

    with open(os.path.join(out_dir, "app_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")

    print("\napid_map for config.toml:")
    for e in spec["entries"]:
        print(f'"{e["apid"]}" = "{e["uid"]}" # {e["name"]}')


if __name__ == "__main__":
    main()
