#!/usr/bin/env python3
"""Generate a zenith per-target config directory from a cFS build.

Reads a spec file describing which telemetry structs to extract from
which ELF files, pulls their exact layouts out of the DWARF debug
info via gdb, and writes the target directory zenith consumes:

    <out>/app_manifest.json      component names, uids, dict joins
    <out>/structs/<comp>.json    one zenith struct dict per component

The layouts come from the same binaries the flight software runs --
not from headers, docs, or memory -- so the dictionaries cannot
drift from the wire. Rerun after any flight software rebuild.

Spec format (JSON):
{
  "application": "cFS cpu1",
  "entries": [
    { "component": "cfe_es",            # dict key (dataFile stem)
      "name": "CFE_ES",                 # display name in zenith
      "elf": "path/to/core-cpu1",       # binary holding the DWARF
      "type": "CFE_ES_HousekeepingTlm_t",
      "apid": "0x000",                  # SPP APID on the wire
      "uid": "0x00C00000" },            # zenith routing uid
    ...
  ]
}

Prints the apid_map block for config.toml when done.

Usage: dictgen.py <spec.json> <output-dir>
"""

import json
import os
import subprocess
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))


def extract(elf: str, entries: list) -> list:
    spec = [{"component": e["component"], "type": e["type"]} for e in entries]
    env = dict(os.environ, DICTGEN_SPEC=json.dumps(spec))
    proc = subprocess.run(
        ["gdb", "-batch", "-nx", "-ex", f"file {elf}",
         "-x", os.path.join(HERE, "gdb_extract.py")],
        capture_output=True, text=True, env=env, check=False,
    )
    out = proc.stdout
    if "DICTGEN_BEGIN" not in out:
        sys.exit(f"gdb extraction failed for {elf}:\n{proc.stderr or out}")
    payload = out.split("DICTGEN_BEGIN")[1].split("DICTGEN_END")[0]
    return json.loads(payload)


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    spec = json.load(open(sys.argv[1]))
    out_dir = sys.argv[2]
    structs_dir = os.path.join(out_dir, "structs")
    os.makedirs(structs_dir, exist_ok=True)

    by_elf = defaultdict(list)
    for e in spec["entries"]:
        by_elf[e["elf"]].append(e)

    results = {}
    for elf, entries in by_elf.items():
        for r in extract(elf, entries):
            results[r["component"]] = r

    manifest = {"application": spec["application"],
                "description": "Generated by cfs-dictgen from build DWARF",
                "components": []}
    for e in spec["entries"]:
        r = results[e["component"]]
        dict_json = {
            "component": e["component"],
            # Stamped from the same binary the layouts come from: the
            # ELF ident declares its own byte order (EI_DATA), so a
            # big-endian flight build generates correct dictionaries
            # with no configuration.
            "byte_order": elf_byte_order(e["elf"]),
            "structs": {
                "Housekeeping": {
                    "category": "TELEMETRY",
                    "size": r["size"],
                    "fields": r["fields"],
                }
            },
        }
        path = os.path.join(structs_dir, f"{e['component']}.json")
        with open(path, "w") as f:
            json.dump(dict_json, f, indent=2)
            f.write("\n")
        manifest["components"].append({
            "name": e["name"],
            "fullUid": e["uid"],
            "type": "telemetry",
            "dataFile": f"{e['component']}.json",
            "notes": f"{r['struct']} from {os.path.basename(e['elf'])}",
        })
        emit = sum(1 for f in r["fields"] if f["type"] in ("uint", "int", "float"))
        print(f"{e['name']}: {r['struct']} -> {r['size']}B payload, "
              f"{len(r['fields'])} fields ({emit} numeric)")

    with open(os.path.join(out_dir, "app_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")

    # Telemetry screen layouts: curated ones pass through from the
    # spec verbatim; otherwise generate one default layout with each
    # component's numeric channels chunked into readable plots. The
    # output directory stays pure generator output either way --
    # curation belongs in the spec, beside the deployment.
    layouts = spec.get("layouts")
    if not layouts:
        plots = []
        for e in spec["entries"]:
            r = results[e["component"]]
            chans = [f"{e['name']}.{f['name']}" for f in r["fields"]
                     if f["type"] in ("uint", "int", "float")]
            for i in range(0, len(chans), 8):
                chunk = chans[i:i + 8]
                n = f" ({i // 8 + 1})" if len(chans) > 8 else ""
                plots.append({"title": f"{e['name']}{n}",
                              "channels": chunk, "height": 200})
        layouts = [{"name": "Default", "plots": plots}]
    with open(os.path.join(out_dir, "telemetry.json"), "w") as f:
        json.dump({"layouts": layouts}, f, indent=2)
        f.write("\n")

    # Connect-time init sequence: the spec declares steps at command
    # level (mid/cc/payload) and the generator packs the wire bytes,
    # so nobody hand-hexes packets. Raw "hex" is accepted for bytes
    # the generator has no builder for.
    if "on_connect" in spec:
        steps = []
        for step in spec["on_connect"]:
            out_step = {"name": step["name"], "delay_ms": step.get("delay_ms", 0)}
            # The command-level fields ride along as provenance so a
            # human opening the file sees WHAT the bytes say, not
            # just the bytes -- same contract split as the struct
            # dicts' layout_hash (contract) + canonical_spec
            # (diagnostic surface). The ground system reads only the
            # hex.
            definition = {k: v for k, v in step.items()
                          if k not in ("name", "delay_ms", "hex")}
            if definition:
                out_step["definition"] = definition
            if "hex" in step:
                out_step["hex"] = step["hex"]
            else:
                out_step["hex"] = cmd_packet_hex(step)
            steps.append(out_step)
        with open(os.path.join(out_dir, "on_connect.json"), "w") as f:
            json.dump({"on_connect": steps}, f, indent=2)
            f.write("\n")
        print(f"\non_connect.json: {len(steps)} step(s): "
              + ", ".join(s["name"] for s in steps))

    print("\napid_map for config.toml:")
    for e in spec["entries"]:
        print(f'"{e["apid"]}" = "{e["uid"]}" # {e["name"]}')


def elf_byte_order(elf: str) -> str:
    """Read the ELF ident's EI_DATA byte: 1 = little-endian, 2 = big."""
    with open(elf, "rb") as f:
        ident = f.read(6)
    if len(ident) < 6 or ident[:4] != b"\x7fELF":
        sys.exit(f"{elf}: not an ELF file")
    if ident[5] == 2:
        return "be"
    return "le"


def cmd_packet_hex(step: dict) -> str:
    """Pack a CCSDS command packet: 6-byte primary header (stream id,
    unsegmented sequence flags, length) + [function code, checksum 0]
    + payload. Checksum stays 0: length is what the lab apps
    validate."""
    mid = int(step["cmd_mid"], 0)
    cc = int(step["cc"])
    if "payload_ascii" in step:
        payload = step["payload_ascii"].encode("ascii")
        payload = payload.ljust(int(step.get("pad_to", len(payload))), b"\0")
    else:
        payload = bytes.fromhex(step.get("payload_hex", ""))
    data_len = 2 + len(payload)
    pkt = bytes([
        (mid >> 8) & 0xFF, mid & 0xFF,
        0xC0, 0x00,
        ((data_len - 1) >> 8) & 0xFF, (data_len - 1) & 0xFF,
        cc, 0,
    ]) + payload
    return pkt.hex()


if __name__ == "__main__":
    main()
