#!/usr/bin/env python3
"""Generate a zenith target directory from an F-prime deployment's
build-generated JSON topology dictionary.

The cleanest of the three generators: F-prime hands us a versioned,
fully-typed dictionary, so this is a pure transform -- no debug-info
extraction, no compile tricks. Output:

    <out>/app_manifest.json    one entry per channel (uid = channel id)
    <out>/structs/ch_*.json    one dict per channel: 17-byte record
                               header + the typed value, byte_order be
    <out>/records.json         the record-routing table for the
                               tm+ccsds-spp+records stack
    <out>/telemetry.json       curated layouts from the spec, or a
                               default chunking per component

Record layout (stock ComCcsds downlink, confirmed on a live capture):
[descriptor U16][channel id U32][time: base U16, ctx U8, secs U32,
useconds U32] = 17 bytes, then the value, big-endian throughout per
F-prime serialization. One dictionary file per channel keeps the
(uid, size) join collision-free when two channels share a value
width.

String channels are variable-length on the wire (length-prefixed)
and are skipped with a warning: a string record's id is absent from
the table, so an aggregate's tail past one is dropped and counted.

Usage: dictgen.py <spec.json> <output-dir>
Spec: { "application": ..., "dictionary": path, "layouts": [...] }
"""

import json
import os
import sys

RECORD_HEADER = 17
DESCRIPTOR_OFFSET_OF_ID = 2
ID_SIZE = 4
TELEMETRY_APID = "0x001"
# Stock F-prime packet types deliberately not decoded (events, files,
# packetized tlm, data products, idle, params, handshake, unknown).
SKIP_APIDS = ["0x002", "0x003", "0x004", "0x005", "0x006", "0x007", "0x0FE", "0x0FF"]


def resolve_type(t: dict, typedefs: dict, depth: int = 0) -> dict | None:
    """Follow alias/enum indirection to a concrete numeric type."""
    if depth > 8:
        return None
    kind = t.get("kind")
    if kind in ("integer", "float", "bool"):
        return t
    if kind == "qualifiedIdentifier":
        td = typedefs.get(t.get("name"))
        if td is None:
            return None
        if td.get("kind") == "alias":
            return resolve_type(td.get("underlyingType", {}), typedefs, depth + 1)
        if td.get("kind") == "enum":
            return resolve_type(td.get("representationType", {}), typedefs, depth + 1)
    return None


def zenith_type(concrete: dict) -> tuple[str, int]:
    size = concrete["size"] // 8
    if concrete["kind"] == "float":
        return "float", size
    if concrete["kind"] == "bool":
        return "uint", max(size, 1)
    return ("int" if concrete.get("signed") else "uint"), size


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    spec = json.load(open(sys.argv[1]))
    fdict = json.load(open(spec["dictionary"]))
    out_dir = sys.argv[2]
    structs_dir = os.path.join(out_dir, "structs")
    os.makedirs(structs_dir, exist_ok=True)

    meta = fdict.get("metadata", {})
    typedefs = {t.get("qualifiedName"): t for t in fdict.get("typeDefinitions", [])}

    manifest = {
        "application": spec.get("application", meta.get("deploymentName", "fprime")),
        "description": (
            f"Generated by fprime-dictgen from {meta.get('deploymentName', '?')} "
            f"(framework {meta.get('frameworkVersion', '?')}, "
            f"dictionary spec {meta.get('dictionarySpecVersion', '?')})"
        ),
        "components": [],
    }
    records = []
    skipped = []
    converted = 0
    for ch in fdict["telemetryChannels"]:
        concrete = resolve_type(ch["type"], typedefs)
        if concrete is None:
            skipped.append((ch["name"], ch["type"].get("kind", "?")))
            continue
        ftype, fsize = zenith_type(concrete)
        cid = ch["id"]
        comp, _, leaf = ch["name"].rpartition(".")
        key = f"ch_0x{cid:08X}"
        dict_json = {
            "component": key,
            "byte_order": "be",
            "structs": {
                "Record": {
                    "category": "TELEMETRY",
                    "size": RECORD_HEADER + fsize,
                    "fields": [
                        {
                            "name": leaf,
                            "type": ftype,
                            "offset": RECORD_HEADER,
                            "size": fsize,
                        }
                    ],
                }
            },
        }
        with open(os.path.join(structs_dir, f"{key}.json"), "w") as f:
            json.dump(dict_json, f, indent=2)
            f.write("\n")
        manifest["components"].append({
            "name": comp or leaf,
            "fullUid": f"0x{cid:08X}",
            "type": "telemetry",
            "dataFile": f"{key}.json",
            "notes": ch.get("annotation", ""),
        })
        records.append({"id": cid, "size": fsize, "uid": f"0x{cid:08X}"})
        converted += 1

    with open(os.path.join(out_dir, "app_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")

    with open(os.path.join(out_dir, "records.json"), "w") as f:
        json.dump({
            "record_apid": TELEMETRY_APID,
            "id_offset": DESCRIPTOR_OFFSET_OF_ID,
            "id_size": ID_SIZE,
            "header_size": RECORD_HEADER,
            "skip_apids": SKIP_APIDS,
            "records": records,
        }, f, indent=2)
        f.write("\n")

    layouts = spec.get("layouts")
    if not layouts:
        # Default: chunk channels per component, 8 per plot.
        plots = []
        per_comp: dict = {}
        for ch in fdict["telemetryChannels"]:
            if resolve_type(ch["type"], typedefs) is None:
                continue
            comp, _, _leaf = ch["name"].rpartition(".")
            per_comp.setdefault(comp, []).append(ch["name"])
        for comp, chans in per_comp.items():
            for i in range(0, len(chans), 8):
                n = f" ({i // 8 + 1})" if len(chans) > 8 else ""
                plots.append({"title": f"{comp}{n}", "channels": chans[i:i + 8],
                              "height": 200})
        layouts = [{"name": "Default", "plots": plots}]
    with open(os.path.join(out_dir, "telemetry.json"), "w") as f:
        json.dump({"layouts": layouts}, f, indent=2)
        f.write("\n")

    print(f"{converted} channels converted, {len(skipped)} skipped:")
    for name, kind in skipped:
        print(f"  skipped {name} ({kind}: variable-length on the wire)")
    print(f"framework {meta.get('frameworkVersion')}, "
          f"dictionary spec {meta.get('dictionarySpecVersion')}")


if __name__ == "__main__":
    main()
